title: Unapologetic Snippets
description: "Crazy Talk: My Disturbing Thoughts Won’t Go Away. What Do I Do?"
repository: igorlima/unapologetic-snippets # for github-metadata
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/igorlima/unapologetic-snippets
