title: Unapologetic Snippets
description: "Crazy Talk: My Disturbing Thoughts Won’t Go Away. What Do I Do?"
repository: igorlima/unapologetic-snippets # for github-metadata
theme: just-the-docs

aux_links:
  Github: https://github.com/igorlima/unapologetic-snippets

nav_external_links:
  - title: Unapologetic Thoughts
    url: https://igorlima.github.io/unapologetic-thoughts/
  - title: Just the Docs
    url: https://just-the-docs.github.io/just-the-docs/
